import 'dart:io';

import 'package:path/path.dart' as p;

class ExistingAgentConfig {
  ExistingAgentConfig({
    required this.hasAgentsFile,
    required this.ruleDocs,
    required this.docsDirectoryExists,
  });

  final bool hasAgentsFile;
  final List<String> ruleDocs;
  final bool docsDirectoryExists;

  bool get found => hasAgentsFile || ruleDocs.isNotEmpty || docsDirectoryExists;
}

class ExistingConfigAdoption {
  static const bridgeStart = '<!-- flutter-agents:bridge:start -->';
  static const bridgeEnd = '<!-- flutter-agents:bridge:end -->';

  ExistingAgentConfig inspect(Directory root) {
    final agents = File(p.join(root.path, 'AGENTS.md'));
    final docs = Directory(p.join(root.path, 'docs'));
    final ruleDocs = <String>[];
    if (docs.existsSync()) {
      for (final entity in docs.listSync(recursive: true, followLinks: false)) {
        if (entity is! File || p.extension(entity.path).toLowerCase() != '.md') continue;
        final rel = p.relative(entity.path, from: root.path);
        ruleDocs.add(rel);
      }
    }
    ruleDocs.sort();
    return ExistingAgentConfig(
      hasAgentsFile: agents.existsSync(),
      ruleDocs: ruleDocs,
      docsDirectoryExists: docs.existsSync(),
    );
  }

  Directory backup(Directory root, Iterable<String> relativePaths) {
    final stamp = DateTime.now().toUtc().toIso8601String().replaceAll(':', '-');
    final backupRoot = Directory(p.join(root.path, '.flutter-agents-backup', stamp));
    for (final rel in relativePaths.toSet()) {
      final source = File(p.join(root.path, rel));
      if (!source.existsSync()) continue;
      final target = File(p.join(backupRoot.path, rel));
      target.parent.createSync(recursive: true);
      target.writeAsBytesSync(source.readAsBytesSync());
    }
    return backupRoot;
  }

  void writeImportedIndex(Directory root, List<String> docs) {
    final file = File(p.join(root.path, 'docs', 'project', 'IMPORTED-RULES.md'));
    file.parent.createSync(recursive: true);
    final b = StringBuffer()
      ..writeln('# Imported Existing Rules')
      ..writeln()
      ..writeln('<!-- GENERATED BY flutter-agents. Existing source files remain user-owned and are never overwritten by the CLI. -->')
      ..writeln()
      ..writeln('Read only the entries relevant to the current task. Existing project rules take precedence over generic CLI profiles.');
    if (docs.isEmpty) {
      b..writeln()..writeln('- No existing Markdown rule docs were detected.');
    } else {
      b.writeln();
      for (final path in docs) {
        b.writeln('- `$path`');
      }
    }
    file.writeAsStringSync(b.toString());
  }

  void removeImportedIndex(Directory root) {
    final file = File(p.join(root.path, 'docs', 'project', 'IMPORTED-RULES.md'));
    if (!file.existsSync()) return;
    final text = file.readAsStringSync();
    if (text.contains('GENERATED BY flutter-agents')) file.deleteSync();
  }

  void addBridgeToExistingAgents(Directory root) {
    final file = File(p.join(root.path, 'AGENTS.md'));
    if (!file.existsSync()) return;
    final current = file.readAsStringSync();
    if (current.contains(bridgeStart)) return;
    final block = '''

$bridgeStart
## flutter-agents integration

For tasks touching CLI-managed concerns, also read `docs/PROJECT-STACK.md` and `docs/ARCHITECTURE-ESSENTIAL.md`. Load only the relevant active profile/custom rule listed there. If `docs/project/IMPORTED-RULES.md` exists, consult only the listed existing project rule documents relevant to the current task.

Existing project rules and this AGENTS.md keep precedence over generic CLI profile guidance.
$bridgeEnd
''';
    file.writeAsStringSync('$current$block');
  }

  void removeBridgeFromExistingAgents(Directory root) {
    final file = File(p.join(root.path, 'AGENTS.md'));
    if (!file.existsSync()) return;
    final text = file.readAsStringSync();
    final start = text.indexOf(bridgeStart);
    final end = text.indexOf(bridgeEnd);
    if (start < 0 || end < start) return;
    final before = text.substring(0, start).trimRight();
    final after = text.substring(end + bridgeEnd.length).trimLeft();
    final merged = after.isEmpty ? '$before\n' : '$before\n\n$after';
    file.writeAsStringSync(merged);
  }
}
